name: oblt-cli
description: Set up oblt-cli and use it in your command
author: https://github.com/elastic
public: true
requirements:
  - jq
  - curl
  - bash
  - tar
  - git
configuration:
  properties:
    version:
      type: string
      description: The version of the plugin to use
    version-file:
      type: string
      description: The file to get the version from. Also supports .tool-versions
    username:
      type: string
      description: The username to use for oblt-cli
    slack-channel:
      type: string
      description: The Slack channel to post notifications to
  additionalProperties: false
