# Config file for `updatecli compose ...`.
# https://www.updatecli.io/docs/core/compose/
policies:
  - name: Handle default oblt-cli version
    policy: ghcr.io/elastic/oblt-updatecli-policies/oblt-cli/version:0.4.0@sha256:2f7214fc2b20f67f2ad4a2dde969c37126e8a023f55361162d6b91996f211a49
    values:
      - updatecli/values.d/scm.yml
      - updatecli/values.d/oblt-cli.yml
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.9.1@sha256:5bbca67a9e31bf5432d5cae1452b9fc770014151ddd856f367ccb9ba46f6f8bb
    values:
      - updatecli/values.d/scm.yml
      - updatecli/values.d/update-compose.yml
