steps:
  - label: ":test_tube: Unit Tests"
    agents:
      provider: gcp
    command: make test

  - label: ":test_tube: Unit Tests (PowerShell)"
    agents:
      provider: gcp
    command: make test-ps

  - label: ":lint-roller: Plugin Lint"
    agents:
      provider: gcp
    command: make plugin-lint

  - label: ":shell: ShellCheck"
    agents:
      provider: gcp
    command: make shellcheck

  - label: integration-test with GITHUB_TOKEN
    agents:
      provider: gcp
    command: make integration-test

  - label: "E2E - Create cluster (Linux AMD64)"
    key: create-cluster
    agents:
      provider: gcp
    plugins:
      - elastic/oblt-cli#${BUILDKITE_COMMIT}:
          version-file: .default-oblt-cli-version
    command: .buildkite/scripts/create-cluster.sh

  - label: "E2E - Get cluster name (Linux AMD64)"
    depends_on: create-cluster
    command: buildkite-agent meta-data get cluster-name

  - label: "E2E - Create cluster (Linux ARM64)"
    agents:
      provider: "aws"
      instanceType: "m6g.medium"
      imagePrefix: "core-ubuntu-2204-aarch64"
    plugins:
      - elastic/oblt-cli#${BUILDKITE_COMMIT}:
          version-file: .default-oblt-cli-version
    command: .buildkite/scripts/create-cluster.sh

  - label: "E2E - Create cluster (Windows AMD64)"
    key: create-cluster-windows
    agents:
      provider: gcp
      image: family/core-windows-2022
    plugins:
      - elastic/oblt-cli#${BUILDKITE_COMMIT}:
          version-file: .default-oblt-cli-version
    command: .buildkite/scripts/create-cluster.ps1

  - label: "E2E - Create cluster (Windows ARM64)"
    key: create-cluster-windows-arm
    agents:
      provider: azure
      image: core-windows-11-ent-arm64
      vmSize: Standard_D4ps_v6
    plugins:
      - elastic/oblt-cli#${BUILDKITE_COMMIT}:
          version-file: .default-oblt-cli-version
    command: .buildkite/scripts/create-cluster.ps1

  - label: "E2E - Get cluster name (Windows AMD64)"
    depends_on: create-cluster-windows
    command: buildkite-agent meta-data get cluster-name

notify:
  - slack: "#observablt-bots"
    if: build.branch == "main" && build.state == "failed"
