steps:
  - label: integration-test with GITHUB_TOKEN
    agents:
      provider: gcp
    command: make integration-test

  - label: "E2E - Create cluster (Linux AMD64)"
    key: create-cluster
    agents:
      provider: gcp
    plugins:
      - elastic/oblt-cli#${BUILDKITE_COMMIT}:
          version-file: .default-oblt-cli-version
    command: .buildkite/scripts/create-cluster.sh

  - label: "E2E - Get cluster name (Linux AMD64)"
    depends_on: create-cluster
    command: buildkite-agent meta-data get cluster-name

  - label: "E2E - Create cluster (Linux ARM64)"
    agents:
      provider: "aws"
      instanceType: "m6g.medium"
      imagePrefix: "core-ubuntu-2204-aarch64"
    plugins:
      - elastic/oblt-cli#${BUILDKITE_COMMIT}:
          version-file: .default-oblt-cli-version
    command: .buildkite/scripts/create-cluster.sh

notify:
  - slack: "#observablt-bots"
    if: build.branch == "main" && build.state == "failed"
