steps:
  - label: integration-test with GITHUB_TOKEN
    agents:
      provider: gcp
    command: make integration-test

  - label: "E2E - Create cluster"
    key: create-cluster
    agents:
      provider: gcp
    plugins:
      - elastic/oblt-cli#${BUILDKITE_COMMIT}:
          version-file: .default-oblt-cli-version
    command: .buildkite/scripts/create-cluster.sh

  - label: "E2E - Get cluster name"
    depends_on: create-cluster
    command: buildkite-agent meta-data get cluster-name

notify:
  - slack: "#observablt-bots"
    if: build.branch == "main" && build.state == "failed"
