#!/usr/bin/env bash

set -euo pipefail

OBLT_CLI_BIN="${HOME}/.oblt-cli/bin"
OBLT_CLI_OUTPUT_FILE="${HOME}/.oblt-cli/output.json"
ELASTIC_APM_ENVIRONMENT="ci"
PATH="${OBLT_CLI_BIN}:${PATH}"

export OBLT_CLI_BIN OBLT_CLI_OUTPUT_FILE ELASTIC_APM_ENVIRONMENT PATH
